apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-visitor
  annotations:
    originImageName: nginx
    deploy.cloud.sealos.io/minReplicas: '1'
    deploy.cloud.sealos.io/maxReplicas: '1'
    deploy.cloud.sealos.io/resize: 0Gi
  labels:
    app: web-visitor
    cloud.sealos.io/app-deploy-manager: web-visitor
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: web-visitor
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: web-visitor
        restartTime: '20260117161338'
    spec:
      automountServiceAccountToken: false
      containers:
        - name: web-visitor
          image: nginx
          env: []
          resources:
            requests:
              cpu: 20m
              memory: 25Mi
            limits:
              cpu: 200m
              memory: 256Mi
          ports:
            - containerPort: 80
              name: wmupxhcdhsky
          imagePullPolicy: Always
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
      volumes:
        - name: nginx-config
          configMap:
            name: web-visitor-nginx-config
